name: deploy_to_gcs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/gcp/composer/**


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/814992956970/locations/global/workloadIdentityPools/zdh-workflow-wi-pool/providers/github'
          service_account: zdh-workflow-action@bold-seat-291901.iam.gserviceaccount.com

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'src'
          destination: 'oh-test'

      # 成功
      - name: 'Teams Notification success on Success'
        if: ${{ success() }}
        run: |
          pip install -r utils/notify_teams/requirements.txt
          python utils/notify_teams/notify_teams.py ${{ secrets.TEAMS_WEBHOOK_URL }} 'success' ${{ github.event.repository.url }} '${{ github.event.head_commit.message }}' '${{ github.event.head_commit.author.name }}' ${{ github.event.head_commit.timestamp }}
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

      # 失敗
      - name: 'Teams Notification failure on failure'
        if: ${{ failure() }}
        run: |
          pip install -r utils/notify_teams/requirements.txt
          python utils/notify_teams/notify_teams.py ${{ secrets.TEAMS_WEBHOOK_URL }} 'failure' ${{ github.event.repository.url }} '${{ github.event.head_commit.message }}' '${{ github.event.head_commit.author.name }}' ${{ github.event.head_commit.timestamp }}
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
