name: Terraform

defaults:
  run:
    working-directory: ./src/gcp/bigquery

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - src/gcp/bigquery/**

jobs:
  deploy:
    name: Deploy BigQuery Datasets
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set auth variables
      run: |
        if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
          echo "WORKLOAD_IDENTITY_PROVIDER='projects/814992956970/locations/global/workloadIdentityPools/zdh-workflow-wi-pool/providers/github'" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=zdh-workflow-action@bold-seat-291901.iam.gserviceaccount.com" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == 'refs/heads/dev' ]]; then
          echo "WORKLOAD_IDENTITY_PROVIDER='projects/[PROJECT_ID]/locations/global/workloadIdentityPools/[POOL_ID]/providers/github'" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=[DEV_SERVICE_ACCOUNT]@[PROJECT_ID].iam.gserviceaccount.com" >> $GITHUB_ENV
        else
          echo "Unsupported branch"
          exit 1
        fi
    
    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Deploy Each Dataset
      run: |
        echo "Initializing Terraform"
        terraform init
    
        echo "Checking Terraform format"
        terraform fmt -check
    
        echo "Planning Terraform changes"
        terraform plan -var-file=environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }}
    
        echo "Applying Terraform changes"
        terraform apply -var-file=environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }} -auto-approve
  
